### PR TITLE
Parse dashed command names properly

### LINKED ISSUE #142: Parsing of hyphenated commands
**Bug** 

Currently if you have a command that includes an additional hyphen, the parsing of the command becomes unexpected.  In the sense that you have a command package of `cli-generate-project-json` this becomes `dojo generate-project json` instead of `dojo generate project-json`.

### PR DESCRIPTION
**Pull request by kitsonk**
**Type:** bug

The following has been addressed in the PR:

* [X] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [X] Unit or Functional tests are included in the PR

**Description:**

This PR fixes issues when a command has a dash in it's name.  Commands like `cli-foo-bar-baz` will be parsed as a group of `foo` and a name of `bar-baz`.  Previously, these were being parsed as `foo-bar` and `baz`.

This will mean that group names cannot be dashed.

Resolves #142

### CODE REVIEW

File: tests/support/dash-names-foo-bar-baz.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export const description = 'test-description';
+export function register() {
+	return 'registered';
+};
+export function	run() {
```
Comment (agubler) [inline tests/support/dash-names-foo-bar-baz.ts]: nit: is this formatting funky?

File: tests/unit/command.ts [hunk 2]
```diff
@@ -122,6 +125,16 @@ registerSuite({
 			}
 		}
 	},
+	'load of commands parsed correctly': {
+		'setup'() {
+			loader = command.initCommandLoader(testSearchPrefixesDashedNames);
+			commandWrapper = loader('../tests/support/dash-names-foo-bar-baz');
```
Comment (agubler) [inline tests/unit/command.ts]: Can you use `getCommandPath`?

File: tests/support/dash-names-foo-bar-baz.ts (hunk 1 above)
Comment (kitsonk) [inline tests/support/dash-names-foo-bar-baz.ts]: It is...

File: tests/unit/command.ts (hunk 2 above)
Comment (kitsonk) [inline tests/unit/command.ts]: No, because it has `const testGroup` and `const testName`.

Comment (agubler) [inline tests/unit/command.ts]: urgh fair enough
