### PR TITLE
Fix unhandled promise rejections

### LINKED ISSUE #150: Clear `UnhandledPromiseRejectionWarning`s from tests.
**Bug**

Currently there are about a dozen `UnhandledPromiseRejectionWarning`s reported by Node.js when running the unit tests, indicating at the very least something is wrong with the tests themselves, or worse with the actual implementation.

Package Version: next

### PR DESCRIPTION
**Pull request by JamesMilnerUK**
**Type:** Bug

The following has been addressed in the PR:

* [X] There is a related issue
* [X] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Resolves #150. It appears the issue was that stub.resolves is used but a promise was being returned back too, creating a double stacked promise. Simply returning a string resolved it.  I've also handled potentially failing promises in the tests themselves, and set process to give a stack trace for any unhandled promises in future.

On another note you still get two 'test error message' from the tests even though it implies they all passed. Any ideas on that? It's the same on master too.

### CODE REVIEW

File: tests/unit/commands/eject.ts [hunk 1]
```diff
@@ -172,6 +183,8 @@ describe('eject command', () => {
 				assert.isTrue(consoleLogStub.getCall(hintsCall).calledWith(underline('\nhints')), 'should underline hints');
 				assert.isTrue(consoleLogStub.getCall(hintsCall + 1).calledWith(' hint 1'), 'should show hint1');
 				assert.isTrue(consoleLogStub.getCall(hintsCall + 2).calledWith(' hint 2'), 'should show hint2');
+			}).catch(() => {
```
Comment (kitsonk) [inline tests/unit/commands/eject.ts]: Minor nit, but would prefer we were consistent in starting chains on a new line.

```
})
.catch(() => {
```

Comment (JamesMilnerUK) [reply tests/unit/commands/eject.ts]: I found a couple other cases in the code base with no new lines, so I fixed those too.
