### PR TITLE
Ensure exit code is non zero when command fails

### LINKED ISSUE #209: A broken test builde returns with exit code zero
**Enhancement**

When building tests with `dojo build -m test` the return code to the operating system is zero even if the build process fails.

Package Version: 0.5.0

**Expected behavior:**

A non zero return code will possibly be more appropriate and ensure that the build breaks a CI build chain.

### PR DESCRIPTION
**Pull request by agubler**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

Exit with non zero code when running a command fails.

Resolves #209

### CODE REVIEW

File: tests/unit/registerCommands.ts [hunk 1]
```diff
@@ -203,26 +209,18 @@ registerSuite('registerCommands', {
...
 					return {
-						beforeEach() {
-							processExitStub = stub(process, 'exit');
-						},
-						afterEach() {
-							processExitStub.restore();
-						},
-
 						tests: {
 							async 'Should not exit process if no status code is returned'() {
```
Comment (agubler) [inline tests/unit/registerCommands.ts]: I should change the name of this test.

Comment (agubler) [reply tests/unit/registerCommands.ts]: and I forgot before I merged :doh:
